### ISSUE TITLE
not found??

### ISSUE THREAD

**Issue by BabyV5** [Phelthas/LXMThirdLoginManager#1]
MacBook:~ mac$ pod search LXMThirdLoginManager
[!] Unable to find a pod with name matching `LXMThirdLoginManager'

**Comment by Phelthas** [comment]
maybe your pod is out of date, try to run `pod setup` first,
![image](https://cloud.githubusercontent.com/assets/8165982/7814377/6b7d3fee-03f4-11e5-871a-94dd13a67895.png)
