### ISSUE TITLE
cocoapods with use_frameworks!

### ISSUE THREAD

**Issue by welkiner** [Phelthas/LXMThirdLoginManager#2]
当开启动态库时，TencentOpenAPI会报错

![1](https://cloud.githubusercontent.com/assets/5791830/21875048/fba24b7e-d8b3-11e6-800d-c7ecb3bc3071.png)
![2](https://cloud.githubusercontent.com/assets/5791830/21875049/febb7f24-d8b3-11e6-84d6-aace95a3ac8e.png)

**Comment by Phelthas** [comment]
@welkiner 
兄弟，看你这报的错是qq不支持模拟器；你是用我pod里面自带的sdk文件吗？还是另外自己下载的？我里面qqsdk用的是2.9.0版本，之后的版本貌似不支持模拟器；
我之前倒是碰到qqsdk的bitCode关闭不了的问题，也是在用了use_frameworks!之后出现的，如果你遇到那个这个问题，可以参考我之前写的 [博客](http://www.cnblogs.com/Phelthas/p/6232036.html)

**Comment by welkiner** [comment]
直接在podfile中导入的，qqsdk 应该只是不支持i386的架构了也就是iPhone5之前的模拟器，x64是支持的，报错是在项目中使用到QQApiInterface才会报错。报错的demo我刚上传了
[demo地址点这里](https://github.com/welkiner/QQFrameworkDemo.git)

![default](https://cloud.githubusercontent.com/assets/5791830/21876054/21c77b38-d8bb-11e6-9d7b-7758ba304010.png)

**Comment by Phelthas** [comment]
@welkiner 
我试了一下，确实有这个问题，貌似是因为qqSDK的原因，只要使用QQApiInterface这个文件就会报错；微博和微信就没问题。。。我也比较无语；
如果你只是为了检测是否安装qq，建议你直接用我提供的方法吧：
`+ (BOOL)isAppInstalledForLoginType:(LXMThirdLoginType)type;`     
我试了一下这样是没问题的；
如果你要用到QQApiInterface的其他方法，那就不好办了。。。让我再研究研究怎么解决，搞定了我会及时更新的

**Comment by Phelthas** [comment]
@welkiner 
过了这么久我终于解决了这个问题，使用use_framework!的时候，所有的pod库都会被编译成framework的形式，如果pod库里面还有依赖其他静态库，那很可能会出现各种编译错误。weiboSDK的库下面也有很多反馈这种问题的。我现在的解决方案是：把这个库的代码直接拖进项目里面，再使用`SwiftSetting`这个subspec来配置依赖。具体readme里面有写。效果还不错，你可以试试
