### ISSUE TITLE
启动app的时候卡死，卡在[WBMFPRSA getPublicKey]

### ISSUE THREAD

**Issue by odyyy** [Phelthas/LXMThirdLoginManager#3]
@大神你好，我是按照你的样子自己写了一个三方库，但是运行起来的时候每次启动的时候会卡死崩溃，我对比了一下我们的文件，好像就是demo工程在设置库的时候你引入了微博的.a文件，我这边无法导入，导入就显示无法查到到libWeiboSDK.a文件，大神你是怎么导入进去的呢。。
<img width="368" alt="q1" src="https://cloud.githubusercontent.com/assets/17714998/22864027/7a70d6e4-f184-11e6-9030-613ef8d0ca53.png">
<img width="575" alt="q2" src="https://cloud.githubusercontent.com/assets/17714998/22864026/7a6c20cc-f184-11e6-94b3-88c0b6276574.png">
<img width="819" alt="q3" src="https://cloud.githubusercontent.com/assets/17714998/22864036/ad991f5e-f184-11e6-9f0f-743910661f56.png">

**Comment by Phelthas** [comment]
@odyyy 你好
我是用cocoapod来导入第三方库的，关键在于LXMThirdLoginManager.podspec这个文件，你可以看看我之前写的[总结](http://www.cnblogs.com/Phelthas/p/4505108.html)；
