### ISSUE TITLE
没有安装应用能否授权和分享

### ISSUE THREAD

**Issue by wujiandao07** [Phelthas/LXMThirdLoginManager#4]
1.目前微博做了网页版的登录，分享还没有做。另外的qq和微信还没有做，不知道是否有网页版的登录和分享功能

**Comment by Phelthas** [comment]
@wujiandao07 官方的sdk分享都必须有装相应app才可以，登录的话qq支持网页登陆，微博支持不支持忘记了，微信不支持网页登陆；如果你想不用官方sdk就实现这些功能的话，可以看看[100apps/openshare](https://github.com/100apps/openshare)这个库。我这个LoginManager是直接把第三方sdk封装到里面的

**Comment by wujiandao07** [comment]
感谢楼主的分享，帮助很大

**Comment by Phelthas** [comment]
@wujiandao07 不用客气，互相学习，共同进步了~
